### PR TITLE
Adding secondary vertex reconstruction

### PR DESCRIPTION
**Pull request by mattleblanc**
Not quite there yet. Currently failing with the following ...

```
[ 83%] Linking CXX shared module ../x86_64-slc6-gcc62-opt/lib/libDerivationFrameworkEoverP.so
CMakeFiles/DerivationFrameworkEoverP.dir/src/Reco_mumu.cxx.o: In function `DerivationFramework::Reco_mumu::addBranches() const':
/home/mleblanc/daod_lambda/src/DerivationFrameworkEoverP/src/Reco_mumu.cxx:113: undefined reference to `Analysis::JpsiFinder::performSearch(DataVector<xAOD::Vertex_v1, DataModel_detail::NoBase>*&, xAOD::VertexAuxContainer_v1*&)'
/home/mleblanc/daod_lambda/src/DerivationFrameworkEoverP/src/Reco_mumu.cxx:145: undefined reference to `DerivationFramework::BPhysPVTools::BPhysPVTools(Trk::V0Tools*, ServiceHandle<IBeamCondSvc> const*)'
/home/mleblanc/daod_lambda/src/DerivationFrameworkEoverP/src/Reco_mumu.cxx:146: undefined reference to `DerivationFramework::BPhysPVTools::SetMinNTracksInPV(unsigned long)'
/home/mleblanc/daod_lambda/src/DerivationFrameworkEoverP/src/Reco_mumu.cxx:158: undefined reference to `DerivationFramework::BPhysPVTools::FillCandExistingVertices(DataVector<xAOD::Vertex_v1, DataModel_detail::NoBase>*, DataVector<xAOD::Vertex_v1, DataModel_detail::NoBase> const*, int)'
/home/mleblanc/daod_lambda/src/DerivationFrameworkEoverP/src/Reco_mumu.cxx:151: undefined reference to `DerivationFramework::BPhysPVTools::FillCandwithRefittedVertices(DataVector<xAOD::Vertex_v1, DataModel_detail::NoBase>*, DataVector<xAOD::Vertex_v1, DataModel_detail::NoBase> const*, DataVector<xAOD::Vertex_v1, DataModel_detail::NoBase>*, Analysis::PrimaryVertexRefitter*, unsigned long, int)'
CMakeFiles/DerivationFrameworkEoverP.dir/src/Reco_mumu.cxx.o: In function `void* SG::BaseInfoImpl<xAOD::Muon_v1>::converterToHelper<xAOD::IParticle>(void*, std::integral_constant<bool, true>)':
/cvmfs/atlas.cern.ch/repo/sw/software/21.0/Athena/21.0.74/InstallArea/x86_64-slc6-gcc62-opt/src/Control/SGTools/SGTools/BaseInfo.icc:165: undefined reference to `typeinfo for xAOD::Muon_v1'
CMakeFiles/DerivationFrameworkEoverP.dir/src/Reco_mumu.cxx.o: In function `Trk::VxSecVertexInfo::clone() const':
/cvmfs/atlas.cern.ch/repo/sw/software/21.0/Athena/21.0.74/InstallArea/x86_64-slc6-gcc62-opt/src/Tracking/TrkEvent/VxSecVertex/VxSecVertex/VxSecVertexInfo.h:83: undefined reference to `Trk::VxSecVertexInfo::VxSecVertexInfo(Trk::VxSecVertexInfo const&)'
CMakeFiles/DerivationFrameworkEoverP.dir/src/Reco_mumu.cxx.o: In function `DataVector_detail::RegisterDVLEltBaseInit<xAOD::Muon_v1>::doinit()':
/cvmfs/atlas.cern.ch/repo/sw/software/21.0/Athena/21.0.74/InstallArea/x86_64-slc6-gcc62-opt/src/Control/AthContainers/AthContainers/tools/DVLEltBaseInfo.icc:111: undefined reference to `typeinfo for xAOD::Muon_v1'
CMakeFiles/DerivationFrameworkEoverP.dir/src/Reco_mumu.cxx.o: In function `ClassName<Trk::TrackParticleBase>::name[abi:cxx11]()':
/cvmfs/atlas.cern.ch/repo/sw/software/21.0/Athena/21.0.74/InstallArea/x86_64-slc6-gcc62-opt/src/Control/SGTools/SGTools/ClassName.icc:24: undefined reference to `typeinfo for Trk::TrackParticleBase'
CMakeFiles/DerivationFrameworkEoverP.dir/src/Reco_mumu.cxx.o: In function `ClassName<Trk::Segment>::name[abi:cxx11]()':
/cvmfs/atlas.cern.ch/repo/sw/software/21.0/Athena/21.0.74/InstallArea/x86_64-slc6-gcc62-opt/src/Control/SGTools/SGTools/ClassName.icc:24: undefined reference to `typeinfo for Trk::Segment'
CMakeFiles/DerivationFrameworkEoverP.dir/src/Reco_mumu.cxx.o: In function `ClassName<xAOD::Muon_v1>::name[abi:cxx11]()':
/cvmfs/atlas.cern.ch/repo/sw/software/21.0/Athena/21.0.74/InstallArea/x86_64-slc6-gcc62-opt/src/Control/SGTools/SGTools/ClassName.icc:24: undefined reference to `typeinfo for xAOD::Muon_v1'
/cvmfs/atlas.cern.ch/repo/sw/software/21.0/Athena/21.0.74/InstallArea/x86_64-slc6-gcc62-opt/src/Control/SGTools/SGTools/ClassName.icc:24: undefined reference to `typeinfo for xAOD::Muon_v1'
CMakeFiles/DerivationFrameworkEoverP.dir/src/Reco_mumu.cxx.o: In function `ClassName<Trk::TrackParticleBase>::name[abi:cxx11]()':
/cvmfs/atlas.cern.ch/repo/sw/software/21.0/Athena/21.0.74/InstallArea/x86_64-slc6-gcc62-opt/src/Control/SGTools/SGTools/ClassName.icc:24: undefined reference to `typeinfo for Trk::TrackParticleBase'
CMakeFiles/DerivationFrameworkEoverP.dir/src/Reco_mumu.cxx.o: In function `ClassName<Trk::Segment>::name[abi:cxx11]()':
/cvmfs/atlas.cern.ch/repo/sw/software/21.0/Athena/21.0.74/InstallArea/x86_64-slc6-gcc62-opt/src/Control/SGTools/SGTools/ClassName.icc:24: undefined reference to `typeinfo for Trk::Segment'
CMakeFiles/DerivationFrameworkEoverP.dir/src/Reco_mumu.cxx.o: In function `SG::BaseInfoImpl<xAOD::Muon_v1>::BaseInfoImpl()':
/cvmfs/atlas.cern.ch/repo/sw/software/21.0/Athena/21.0.74/InstallArea/x86_64-slc6-gcc62-opt/src/Control/SGTools/SGTools/BaseInfo.icc:243: undefined reference to `typeinfo for xAOD::Muon_v1'
CMakeFiles/DerivationFrameworkEoverP.dir/src/Reco_mumu.cxx.o: In function `ClassName<xAOD::Muon_v1>::name[abi:cxx11]()':
/cvmfs/atlas.cern.ch/repo/sw/software/21.0/Athena/21.0.74/InstallArea/x86_64-slc6-gcc62-opt/src/Control/SGTools/SGTools/ClassName.icc:24: undefined reference to `typeinfo for xAOD::Muon_v1'
CMakeFiles/DerivationFrameworkEoverP.dir/src/Reco_mumu.cxx.o: In function `ToolHandle<Trk::V0Tools>::retrieve(Trk::V0Tools*&) const':
/cvmfs/atlas.cern.ch/repo/sw/software/21.0/GAUDI/21.0.74/InstallArea/x86_64-slc6-gcc62-opt/include/GaudiKernel/ToolHandle.h:187: undefined reference to `typeinfo for Trk::V0Tools'
CMakeFiles/DerivationFrameworkEoverP.dir/src/Reco_mumu.cxx.o: In function `ToolHandle<Analysis::PrimaryVertexRefitter>::retrieve(Analysis::PrimaryVertexRefitter*&) const':
/cvmfs/atlas.cern.ch/repo/sw/software/21.0/GAUDI/21.0.74/InstallArea/x86_64-slc6-gcc62-opt/include/GaudiKernel/ToolHandle.h:187: undefined reference to `typeinfo for Analysis::PrimaryVertexRefitter'
CMakeFiles/DerivationFrameworkEoverP.dir/src/Reco_mumu.cxx.o: In function `ToolHandle<Analysis::JpsiFinder>::retrieve(Analysis::JpsiFinder*&) const':
/cvmfs/atlas.cern.ch/repo/sw/software/21.0/GAUDI/21.0.74/InstallArea/x86_64-slc6-gcc62-opt/include/GaudiKernel/ToolHandle.h:187: undefined reference to `typeinfo for Analysis::JpsiFinder'
CMakeFiles/DerivationFrameworkEoverP.dir/src/Reco_mumu.cxx.o:(.data.rel.ro._ZTVN3Trk15VxSecVertexInfoE[_ZTVN3Trk15VxSecVertexInfoE]+0x18): undefined reference to `Trk::VxSecVertexInfo::~VxSecVertexInfo()'
CMakeFiles/DerivationFrameworkEoverP.dir/src/Reco_mumu.cxx.o:(.data.rel.ro._ZTVN3Trk15VxSecVertexInfoE[_ZTVN3Trk15VxSecVertexInfoE]+0x20): undefined reference to `Trk::VxSecVertexInfo::~VxSecVertexInfo()'
CMakeFiles/DerivationFrameworkEoverP.dir/src/components/DerivationFrameworkEoverP_entries.cxx.o: In function `ClassName<xAOD::Muon_v1>::name[abi:cxx11]()':
/cvmfs/atlas.cern.ch/repo/sw/software/21.0/Athena/21.0.74/InstallArea/x86_64-slc6-gcc62-opt/src/Control/SGTools/SGTools/ClassName.icc:24: undefined reference to `typeinfo for xAOD::Muon_v1'
collect2: error: ld returned 1 exit status
make[2]: *** [x86_64-slc6-gcc62-opt/lib/libDerivationFrameworkEoverP.so] Error 1
make[1]: *** [DerivationFrameworkEoverP/CMakeFiles/DerivationFrameworkEoverP.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 84%] Linking CXX shared library ../../../x86_64-slc6-gcc62-opt/lib/libPrimaryDPDMakerLib.so
Detaching debug info of libPrimaryDPDMakerLib.so into libPrimaryDPDMakerLib.so.dbg
[ 84%] Built target PrimaryDPDMakerLib
/cvmfs/sft.cern.ch/lcg/contrib/bintuils/2.28/x86_64-slc6/bin/ld: cannot find -lxAODBPhysLib
/cvmfs/sft.cern.ch/lcg/contrib/bintuils/2.28/x86_64-slc6/bin/ld: cannot find -lBPhysToolsLib
collect2: error: ld returned 1 exit status
make[2]: *** [x86_64-slc6-gcc62-opt/lib/libDerivationFrameworkEoverPLib.so] Error 1
make[1]: *** [DerivationFrameworkEoverP/CMakeFiles/DerivationFrameworkEoverPLib.dir/all] Error 2
make: *** [all] Error 2
```

### CODE REVIEW

**Comment by mattleblanc** [comment]
Seeing similar errors -- feel free to work your magic if you get a chance, @luadamek !

```
[ 94%] Linking CXX shared module ../x86_64-slc6-gcc62-opt/lib/libDerivationFrameworkEoverP.so
CMakeFiles/DerivationFrameworkEoverP.dir/src/Select_onia2mumu.cxx.o: In function `DerivationFramework::Select_onia2mumu::ProcessVertex(xAOD::BPhysHypoHelper&, xAOD::BPhysHelper::pv_type) const':
/home/mleblanc/daod_lambda/src/DerivationFrameworkEoverP/src/Select_onia2mumu.cxx:82: undefined reference to `xAOD::BPhysHypoHelper::setTau(float, xAOD::BPhysHelper::pv_type, xAOD::BPhysHypoHelper::tau_type)'
/home/mleblanc/daod_lambda/src/DerivationFrameworkEoverP/src/Select_onia2mumu.cxx:86: undefined reference to `xAOD::BPhysHypoHelper::setTauErr(float, xAOD::BPhysHelper::pv_type, xAOD::BPhysHypoHelper::tau_type)'
/home/mleblanc/daod_lambda/src/DerivationFrameworkEoverP/src/Select_onia2mumu.cxx:90: undefined reference to `xAOD::BPhysHypoHelper::setTau(float, xAOD::BPhysHelper::pv_type, xAOD::BPhysHypoHelper::tau_type)'
/home/mleblanc/daod_lambda/src/DerivationFrameworkEoverP/src/Select_onia2mumu.cxx:94: undefined reference to `xAOD::BPhysHypoHelper::setTauErr(float, xAOD::BPhysHelper::pv_type, xAOD::BPhysHypoHelper::tau_type)'
/home/mleblanc/daod_lambda/src/DerivationFrameworkEoverP/src/Select_onia2mumu.cxx:102: undefined reference to `xAOD::BPhysHypoHelper::setTau(float, xAOD::BPhysHelper::pv_type, xAOD::BPhysHypoHelper::tau_type)'
/home/mleblanc/daod_lambda/src/DerivationFrameworkEoverP/src/Select_onia2mumu.cxx:105: undefined reference to `xAOD::BPhysHypoHelper::setTauErr(float, xAOD::BPhysHelper::pv_type, xAOD::BPhysHypoHelper::tau_type)'
/home/mleblanc/daod_lambda/src/DerivationFrameworkEoverP/src/Select_onia2mumu.cxx:109: undefined reference to `xAOD::BPhysHypoHelper::setTau(float, xAOD::BPhysHelper::pv_type, xAOD::BPhysHypoHelper::tau_type)'
/home/mleblanc/daod_lambda/src/DerivationFrameworkEoverP/src/Select_onia2mumu.cxx:113: undefined reference to `xAOD::BPhysHypoHelper::setTauErr(float, xAOD::BPhysHelper::pv_type, xAOD::BPhysHypoHelper::tau_type)'
collect2: error: ld returned 1 exit status
make[2]: *** [x86_64-slc6-gcc62-opt/lib/libDerivationFrameworkEoverP.so] Error 1
make[1]: *** [DerivationFrameworkEoverP/CMakeFiles/DerivationFrameworkEoverP.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by luadamek** [comment]
@mattleblanc I believe that the Select_onia2mumu and the BPhysHypoHelper files are incompatible. The listed functions in that error are not defined in BPhysHypoHelper. Did both of these files come from branch 21.2?

**Comment by luadamek** [comment]
@mattleblanc I did a quick check, and the files were not from 21.2. I changed them and it compiles! :) 👍Let me know if the secondary vertices show up in the derivation.

**Comment by mattleblanc** [comment]
This compiles and runs! It's literally amazing. I don't see the containers in the output, but this should be a more manageable problem.

Thanks again for the help!

**Comment by luadamek** [comment]
@mattleblanc I think there are the lines that you want to change in TrackCaloDecorator.py:
#====================================================================
# CREATE THE DERIVATION KERNEL ALGORITHM AND PASS THE ABOVE TOOLS
#====================================================================
from DerivationFrameworkCore.DerivationFrameworkCoreConf import DerivationFramework__DerivationKernel
DerivationFrameworkJob += CfgMgr.DerivationFramework__DerivationKernel("TrackCaloDecorator_KERN", AugmentationTools = [CaloDeco])
topSequence += DerivationFrameworkJob
EOPStream.AcceptAlgs(["TrackCaloDecorator_KERN"])

I think you might have to add your tool as another augmentation tool.

**Comment by mattleblanc** [comment]
Got 'em.

```
http://atlas-computing.web.cern.ch/atlas-computing/links/nightlyDocDirectory/xAODVertex/html/
xAOD::VertexContainer
  |     xAOD::VertexContainer* LambdaCandidates
  |       |     float &->chiSquared()
  |       |     vector<float> &->covariance()
  |       |     vector<ElementLink<DataVector<xAOD::NeutralParticle> > > &->neutralParticleLinks()
  |       |     vector<float> &->neutralWeights()
  |       |     float &->numberDoF()
  |       |     vector<ElementLink<DataVector<xAOD::TrackParticle> > > &->trackParticleLinks()
  |       |     vector<float> &->trackWeights()
  |       |     short &->vertexType()
  |       |     float &->x()
  |       |     float &->y()
  |       |     float &->z()
  |       |     &->getAttribute<float>("A0ErrMaxSumPt2")
  |       |     &->getAttribute<float>("A0MaxSumPt2")
  |       |     &->getAttribute<float>("A0xyErrMaxSumPt2")
  |       |     &->getAttribute<float>("A0xyMaxSumPt2")
  |       |     &->getAttribute<float>("Lambda_mass")
  |       |     &->getAttribute<float>("Lambda_massErr")
  |       |     &->getAttribute<float>("Lambda_TauConstMassPVMaxSumPt2")
  |       |     &->getAttribute<float>("Lambda_TauConstMassPVMinA0")
  |       |     &->getAttribute<float>("Lambda_TauConstMassPVMinZ0")
  |       |     &->getAttribute<float>("Lambda_TauErrConstMassPVMaxSumPt2")
  |       |     &->getAttribute<float>("Lambda_TauErrConstMassPVMinA0")
  |       |     &->getAttribute<float>("Lambda_TauErrConstMassPVMinZ0")
  |       |     &->getAttribute<float>("Lambda_TauErrInvMassPVMaxSumPt2")
  |       |     &->getAttribute<float>("Lambda_TauErrInvMassPVMinA0")
  |       |     &->getAttribute<float>("Lambda_TauErrInvMassPVMinZ0")
  |       |     &->getAttribute<float>("Lambda_TauInvMassPVMaxSumPt2")
  |       |     &->getAttribute<float>("Lambda_TauInvMassPVMinA0")
  |       |     &->getAttribute<float>("Lambda_TauInvMassPVMinZ0")
  |       |     &->getAttribute<float>("LxyErrMaxSumPt2")
  |       |     &->getAttribute<float>("LxyMaxSumPt2")
  |       |     &->getAttribute<char>("passed_Lambda")
  |       |     &->getAttribute<float>("PtErr")
  |       |     &->getAttribute<Int_t>("PvMaxSumPt2Link")
  |       |     &->getAttribute<UInt_t>("PvMaxSumPt2Link.m_persIndex")
  |       |     &->getAttribute<UInt_t>("PvMaxSumPt2Link.m_persKey")
  |       |     &->getAttribute<int>("PvMaxSumPt2Status")
  |       |     &->getAttribute<vector<float>>("RefTrackPx")
  |       |     &->getAttribute<vector<float>>("RefTrackPy")
  |       |     &->getAttribute<vector<float>>("RefTrackPz")
  |       |     &->getAttribute<float>("Z0ErrMaxSumPt2")
  |       |     &->getAttribute<float>("Z0MaxSumPt2")
  |       --------------------
```

**Comment by mattleblanc** [comment]
To confirm, the SV container content is different from the PV container, and it is also non-zero. ;)

This is ready to roll!

**Comment by luadamek** [comment]
That's great to hear! I'll produce some test DAODs for the single low-mu run + MC that we have

**Pull request merged**
